# Generated by Django 4.1.6 on 2023-03-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_taskmodel_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="priority",
            field=models.CharField(
                choices=[("1", "ВЫСОКИЙ"), ("2", "СРЕДНИЙ"), ("3", "НИЗКИЙ")],
                default="1",
                max_length=10,
            ),
        ),
    ]
