# Generated by Django 4.1.6 on 2023-03-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_taskmodel_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="priority",
            field=models.CharField(
                choices=[("1", "TOP"), ("2", "MID"), ("3", "LOW")],
                default="2",
                max_length=10,
            ),
        ),
    ]
