# Generated by Django 4.1.6 on 2023-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_taskmodel_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="priority",
            field=models.CharField(
                choices=[("TOP", "1"), ("MID", "2"), ("LOW", "3")],
                default="MID",
                max_length=10,
            ),
        ),
    ]
